# Generated by Django 5.2.1 on 2025-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('aliados', models.CharField(max_length=200)),
                ('inimigos', models.CharField(max_length=200)),
                ('afiliacao', models.CharField(max_length=200)),
            ],
        ),
    ]
