# Generated by Django 5.2.1 on 2025-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='imagem',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
